### ISSUE TITLE
Unable to send to Event Hub

### ISSUE THREAD

**Issue by wmmihaa** [noodlefrenzy/node-amqp10#179] opened 2015-10-24 20:17 UTC
Trying to send a message to eventhub, but the message is never sent. I've also tried using the simple_eventhub_test.js, which receives messages but can't send any. Using service bus explorer or the .Net api works fine.

``` javascript
'use strict';
var AMQPClient = require('amqp10').Client, Policy = require('amqp10').Policy;

var settings = settings = {
    serviceBusHost: "[namespace].servicebus.windows.net",
    eventHubName: "[eventHubName]",
    SASKeyName: "[SASKeyName]",
    SASKey: "[SASKey]"
};

var uri = 'amqps://' + encodeURIComponent(settings.SASKeyName) + ':' + encodeURIComponent(settings.SASKey) + '@' + settings.serviceBusHost;
var client = new AMQPClient(Policy.EventHub);

var msgVal = Math.floor(Math.random() * 1000000);

client.connect(uri)
  .then(function () { return client.createSender(settings.eventHubName); })
  .then(function (sender) {
    sender.on('errorReceived', function (err) { console.warn(err); });
    return sender.send({ "DataString": "From Node", "DataValue": msgVal });
})
  .then(function (state) { console.log('State: ', state); });
```
Running with debug output gives me this:
https://gist.github.com/wmmihaa/5ca9a3593ffd92e55e10

**Comment by mbroadst** [comment] 2015-10-27 12:06
Just to make sure we track this for future users, @noodlefrenzy responded on gitter with:

```
@wmmihaa hey there, using your exact code and my Event Hub, I was able to send a message successfully. Can you verify that your SAS key is set up with Send permissions? Usually I set up a separate key with _just_ Send permissions, another with _just_ Receive permissions, and a third with both if I need it.
```

**Comment by timfpark** [comment] 2015-11-01 16:13
I'm seeing the same thing with the code in issue #181 and using a SAS key with Send permissions (I confirmed this).  I put the DEBUG=* output in https://gist.github.com/timfpark/42d34d64202a1eb2b699

**Comment by noodlefrenzy** [comment] 2015-11-03 21:37
@timfpark and @wmmihaa - can you please try v2.0.4 (just published)? It has a fix for the message-format of transfer frames that we were incorrectly (not) setting, and apparently EH had tightened their policies on that.

**Comment by timfpark** [comment] 2015-11-03 22:10
@noodlefrenzy: works for me now with v2.0.4 - thanks for the fix!

**Comment by mbroadst** [comment] 2015-11-05 13:23
I think we have almost certainly identified this was because the message format wasn't being sent, which it is now, so I'm going to close this one out. Please reopen if you continue to have trouble @wmmihaa, thanks!

**Closed by mbroadst** 2015-11-05 13:23 UTC
