### ISSUE TITLE
event hub receiver always pulls old messages

### ISSUE THREAD

**Issue by cjpraful** [noodlefrenzy/node-amqp10#164] opened 2015-09-22 13:29 UTC
HI i am trying to receive message from event hub.When  I ran the example program "simple_eventhub_test.js", i was receiving the old messages. Is it the normal behaviour? is there any alternative to restrict messages to unconsumed message or new messages.

**Comment by mbroadst** [comment] 2015-09-22 13:33
@cjpraful hey, this is most likely because v1.0.x isn't sending proper disposition messages. Could you please try your use case with v2.0.0 (master) and confirm the same behavior?

**Comment by mbroadst** [comment] 2015-09-22 18:18
@cjpraful if you're having trouble using master, update your package.json dependencies as follows:
```
"dependencies": {
   ... other deps ...
   "amqp10": "noodlefrenzy/node-amqp10#master"
}
```

**Comment by noodlefrenzy** [comment] 2015-09-22 18:22
Hey @cjpraful that's kind of expected with Event Hubs (http://www.mikelanzetta.com/2014/11/talking-to-eventhub-with-amqp-1-0/) - basically if you don't specify an offset to start with, it'll start from it's earliest known message.

If you look at the returned message annotations, you should see an offset in them, and you can give that back the next time you connect. Alternately, there's an X-header for specifying dates, but I don't remember what it is - trying to find it, and once I do I'll report back.

**Comment by noodlefrenzy** [comment] 2015-09-22 19:09
@cjpraful - the filters are outlined in the AMQPNetLite documentation: https://github.com/Azure/amqpnetlite/wiki/Azure%20Service%20Bus%20Event%20Hubs - that's written by someone on the EH team, so he knows what he's talking about :)

I'll try and get some time to write integration tests against the different filters for v2, but it'll be a few days. Let me know if you get a chance to try them out and run into issues. Specifically - open new issues on the repo, I'll close this one since it's "by design" on their end.

**Closed by noodlefrenzy** 2015-09-22 19:09 UTC

**Comment by cjpraful** [comment] 2015-09-23 05:10
@mbroadst i used the latest branch and tried with the changes you mentioned. It pulls the same old messages again.
@noodlefrenzy Could you please guide me what changes or addition i have to make on the example program to retrieve the latest messages i.e how to set the offset value or header
