### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by markusahlstrand** [noodlefrenzy/node-amqp10#139] opened 2015-08-02 20:24 UTC
From time to time the amqp-client throws the following error even though there are no messages being sent at the time:

```
Application has thrown an uncaught exception and is terminated:
TypeError: Cannot read property 'length' of undefined
    at AMQPClient._resolveDeferredSenderAttaches (D:\home\site\wwwroot\node_modules\amqp10\lib\amqp_client.js:200:41)
    at SenderLink.onAttached (D:\home\site\wwwroot\node_modules\amqp10\lib\amqp_client.js:283:14)
    at SenderLink.emit (events.js:95:17)
    at SenderLink.Link._attachReceived (D:\home\site\wwwroot\node_modules\amqp10\lib\link.js:129:8)
    at SenderLink._attachReceived (D:\home\site\wwwroot\node_modules\amqp10\lib\sender_link.js:154:47)
    at Session._processFrame (D:\home\site\wwwroot\node_modules\amqp10\lib\session.js:303:37)
    at Connection._processFrameEH (D:\home\site\wwwroot\node_modules\amqp10\lib\session.js:201:49)
    at Connection.emit (events.js:117:20)
    at Connection._receiveAny (D:\home\site\wwwroot\node_modules\amqp10\lib\connection.js:446:16)
    at Connection._receiveData (D:\home\site\wwwroot\node_modules\amqp10\lib\connection.js:367:8)
    at CleartextStream.<anonymous> (D:\home\site\wwwroot\node_modules\amqp10\lib\connection.js:529:10)
    at CleartextStream.emit (events.js:95:17)
    at CleartextStream.<anonymous> (_stream_readable.js:764:14)
    at CleartextStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at _stream_readable.js:419:7
```

Will the client reconnect and I can safely just handle those errors?

Thanks

**Comment by mbroadst** [comment] 2015-08-03 16:00
Yeah those errors actually shouldn't be affecting your connections, but either way the current PR up for link attachment refactoring will remove all of these calls. Apologies for the growing pains :smile:

**Comment by markusahlstrand** [comment] 2015-08-03 20:28
This may or may not be related to the issue i opened:
It seems that if there are no messages sent for a certain amount of time the connection disconnects as seen in the logs:
```
Mon, 03 Aug 2015 20:10:11 GMT amqp10:client disconnected
Mon, 03 Aug 2015 20:10:11 GMT amqp10:connection Transitioning from CLOSE_RCVD to DISCONNECTED due to sendClose
Mon, 03 Aug 2015 20:10:11 GMT amqp10:client connection error:  { descriptor: [Int64 value:29 octets:00 00 00 00 00 00 00 1d],
  value: undefined,
  condition: { contents: 'amqp:connection:forced' },
  description: 'The connection was inactive for more than the allowed period of time. TrackingId:ec3bf72e10004dd1b975131050b8f6cf_G28,TimeStamp:8/3/2015 8:10:11 PM',
  errorInfo: null }
```

After that all messages being sent are stuck in the _pendingSends array as the state of the connection link is detached. Guess the disconnect-event should trigger a new connect?

**Comment by mbroadst** [comment] 2015-08-03 20:35
@noodlefrenzy it looks like we have an issue here: https://github.com/noodlefrenzy/node-amqp10/blob/master/lib/amqp_client.js#L146.

The reconnect logic is only triggered on a `Connection.Disconnected` but this is coming in as an error from SB

**Comment by noodlefrenzy** [comment] 2015-08-04 15:45
Ok, I've run some tests against this and run into two different errors:
1) ServiceBus severs the connection properly - we tear everything down and restart it, but at that point the link the client has is disconnected and there's an internal, inaccessible link in its place. There are two options here:
- [ ] we keep our reconnect logic, and just do what we were talking about a bit ago and make sure sessions/links aren't thrown away, but reconnect themselves.
- [ ] we drop the reconnect logic, and just make sure the client knows what happened and they can build a new connection + link.

I'm voting for the first option.

2) ServiceBus severs the connection via a session error - we tear everything down. I'm not quite sure what to do with this one. In theory we should also reconnect here. I'll see what that would take. This seems to be far less frequent (only saw it when trying to debug), so yay, but also makes it difficult to repro and test whether I've fixed it.

**Comment by mbroadst** [comment] 2015-08-04 15:50
On the first point: I think I'm down with option one, but I'm also not clear as to why there are incorrect links in place. On disconnect aren't we clearing connection state (i.e. totally blowing away the session, and therefore all the links)?

Second point: yes I think we should always strive for reconnect based on the reconnect policy settings. This might be as simple as ensuring that eventually the Connection emits Connection.Disconnected after an error occurs (it only seems to emit the error, and that's why the reconnect logic isn't triggered). Alternatively, you could refactor the reconnect logic into a single method and call it from both places, but I feel like the previous suggested approach is more fool-proof

**Comment by markusahlstrand** [comment] 2015-08-04 19:35
I get the session error consistently at exactly 10 minutes of idle time after the last messages is sent. 5 minutes after that I get a connection error.

Last message being sent:
```
Tue, 04 Aug 2015 18:07:51 GMT amqp10:link:sender sending:
```

And here are the session error:
```
Tue, 04 Aug 2015 18:17:51 GMT amqp10:client session error:  { descriptor: [Int64 value:29 octets:00 00 00 00 00 00 00 1d],
  value: undefined,
  condition: { contents: 'amqp:link:detach-forced' },
  description: 'The link \'G4:78791:interactions_TX\' is force detached by the broker due to errors occurred in publisher(link8627). Detach origin: AmqpMessagePublisher.IdleTimerExpired: Idle timeout: 00:10:00. TrackingId:38ea6f3a00000322000021b355c0fe94_G4_B25,TimeStamp:8/4/2015 6:17:51 PM',
  errorInfo: null }
```

and connection error:

```
Tue, 04 Aug 2015 18:22:51 GMT amqp10:client connection error:  { descriptor: [Int64 value:29 octets:00 00 00 00 00 00 00 1d],
  value: undefined,
  condition: { contents: 'amqp:connection:forced' },
  description: 'The connection was inactive for more than the allowed period of time. TrackingId:8913e10bde854f3b86665f37a63116d6_G4,TimeStamp:8/4/2015 6:22:51 PM',
  errorInfo: null }
```

It the reconnects and seems fine but the state of the link I have a refrence to is still detached. Is this because the sender_link that my client has a reference to is actually still detached and there is a brand new one is created instead (which I don't have a reference to..)? If this is so, can I then catch the session/connection-event and get a hold of the new sender_link somehow?

**Comment by noodlefrenzy** [comment] 2015-08-04 20:41
Yes you can! You can actually just listen on the sender link's `detached` method and then do a full tearndown/setup to avoid the problem - since it drops the link before it drops (and then restarts) the connection.

e.g. something like this?
```
function mySenderSetup() {
  client.connect(uri).then(function() {
    return client.createSender(queue);
  }).then(function (sender) {
    sender.on('detached', function() {
      client.disconnect().then(mySenderSetup);
    });
    // do stuff with sender.
  });
}
```

In the meantime, I _am_ working on a fix, but not sure how long it'll take me (since this is my side project I tend to get distracted).

**Comment by markusahlstrand** [comment] 2015-08-04 20:59
Clever, my approach was a bit more crude:) I'll give that a try.

For a side project I think you're very responsive. Thanks

**Comment by noodlefrenzy** [comment] 2015-08-04 21:00
I would've responded more quickly, but I kept having to wait for the timeouts ;-)

**Comment by noodlefrenzy** [comment] 2015-08-07 01:13
Hey @markusahlstrand - I've added some logic in there to auto-reattach Links when ServiceBus does it's detach maneuver - can you try updating to the latest in master and see if it works?

You can see here: https://github.com/noodlefrenzy/node-amqp10/blob/master/examples/servicebus_reconnect.js
I've tested both re-attaching the links, and then (if I disable that) re-connecting and they both work, but I'd love to get some in-the-field feedback.

**Comment by markusahlstrand** [comment] 2015-08-10 09:20
Hi @noodlefrenzy ,

It seems to be reconnecting fine in most cases now, but instead I get the following error if I leave it without sending messages for a while:
```
Mon, 10 Aug 2015 08:01:59 GMT amqp10:client connected
Mon, 10 Aug 2015 08:01:59 GMT amqp10:client session already exists, re-using
Mon, 10 Aug 2015 08:01:59 GMT amqp10:framing:amqp Encoding performative: {"descriptor":{"buffer":{"type":"Buffer","data":[0,0,0,0,0,0,0,17]},"offset":0},"value":{"remoteChannel":null,"nextOutgoingId":{"typeName":"uint","value":1},"incomingWindow":{"typeName":"uint","value":100},"outgoingWindow":{"typeName":"uint","value":100},"handleMax":{"typeName":"uint","value":4294967295},"offeredCapabilities":null,"desiredCapabilities":null,"properties":{},"encodeOrdering":["remoteChannel","nextOutgoingId","incomingWindow","outgoingWindow","handleMax","offeredCapabilities","desiredCapabilities","properties"]}}
Mon, 10 Aug 2015 08:01:59 GMT amqp10:framing Sending frame: BeginFrame: {"type":"Buffer","data":[0,0,0,31,2,0,0,22,0,83,17,192,18,8,64,82,1,82,100,82,100,112,255,255,255,255,64,64,193,1,0]}: 0000001f02000016005311c012084052015264526470ffffffff4040c10100
undefined
/Users/markus/Projects/interaction/node_modules/amqp10/lib/frames/frame.js:87
  outStream.write(buffer);
           ^
TypeError: Cannot read property 'write' of null
    at BeginFrame.Frame.write (/Users/markus/Projects/interaction/node_modules/amqp10/lib/frames/frame.js:87:12)
    at Connection.sendFrame (/Users/markus/Projects/interaction/node_modules/amqp10/lib/connection.js:337:9)
    at Session.begin (/Users/markus/Projects/interaction/node_modules/amqp10/lib/session.js:200:19)
    at Connection.<anonymous> (/Users/markus/Projects/interaction/node_modules/amqp10/lib/amqp_client.js:147:21)
    at Connection.emit (events.js:107:17)
    at Connection._processOpenFrame (/Users/markus/Projects/interaction/node_modules/amqp10/lib/connection.js:494:10)
    at Connection._receiveAny (/Users/markus/Projects/interaction/node_modules/amqp10/lib/connection.js:441:16)
    at Connection._receiveData (/Users/markus/Projects/interaction/node_modules/amqp10/lib/connection.js:367:8)
    at TLSSocket.<anonymous> (/Users/markus/Projects/interaction/node_modules/amqp10/lib/connection.js:529:10)
    at TLSSocket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at TLSSocket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

**Comment by noodlefrenzy** [comment] 2015-08-10 16:39
@markusahlstrand Hmm, that's not good. My _guess_ is this might be us trying to send a heartbeat frame while we're in the middle of a reconnect, which would be bad. However, that's just a guess - I'm investigating.

**Comment by noodlefrenzy** [comment] 2015-08-11 15:00
Hey @markusahlstrand , I just checked in some code to try and harden the heartbeat logic against sending frames during transitional periods like reconnects. I have a multi-day burn test running at work, but I'd love it if you could try it out as well.

**Comment by markusahlstrand** [comment] 2015-08-11 15:01
Thanks @noodlefrenzy ! I'll try out the code tomorrow.

**Comment by markusahlstrand** [comment] 2015-08-13 21:10
Hi @noodlefrenzy ,

Had it running for a while today and got the same error. Looking a bit more closely to the logs there is another error further up the log (same second though) which might be related:
```
Thu, 13 Aug 2015 15:13:48 GMT amqp10:connection Transitioning from START to IN_SASL due to connected
Thu, 13 Aug 2015 15:13:48 GMT amqp10:connection Rx: 414d515003010000
Thu, 13 Aug 2015 15:13:48 GMT amqp10:sasl Server SASL Version: 414d515003010000 vs 414d515003010000
Thu, 13 Aug 2015 15:13:48 GMT amqp10:connection Error from socket: Error: read ECONNRESET
Thu, 13 Aug 2015 15:13:48 GMT amqp10:client connection error:  { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
Thu, 13 Aug 2015 15:13:48 GMT amqp10:client disconnected
Thu, 13 Aug 2015 15:13:48 GMT amqp10:connection Transitioning from IN_SASL to DISCONNECTED due to error
Unhandled rejection AmqpOverCapacityError: Out of available handles (Max = undefined)
    at Session._nextHandle (/Users/markus/Projects/interaction/node_modules/amqp10/lib/session.js:291:9)
    at Session.createLink (/Users/markus/Projects/interaction/node_modules/amqp10/lib/session.js:206:32)
    at AMQPClient.createSender.attach (/Users/markus/Projects/interaction/node_modules/amqp10/lib/amqp_client.js:209:32)
    at AMQPClient.createSender (/Users/markus/Projects/interaction/node_modules/amqp10/lib/amqp_client.js:213:5)
    at tryCatcher (/Users/markus/Projects/interaction/node_modules/amqp10/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.module.exports.Promise._resolveFromResolver (/Users/markus/Projects/interaction/node_modules/amqp10/node_modules/bluebird/js/main/promise.js:476:31)
    at new Promise (/Users/markus/Projects/interaction/node_modules/amqp10/node_modules/bluebird/js/main/promise.js:69:37)
    at AMQPClient.createSender (/Users/markus/Projects/interaction/node_modules/amqp10/lib/amqp_client.js:202:10)
    at AMQPClient.<anonymous> (/Users/markus/Projects/interaction/services/serviceBus.js:11:9)
    at AMQPClient.emit (events.js:107:17)
    at Connection.<anonymous> (/Users/markus/Projects/interaction/node_modules/amqp10/lib/amqp_client.js:331:10)
    at Connection.emit (events.js:107:17)
    at Connection._processError (/Users/markus/Projects/interaction/node_modules/amqp10/lib/connection.js:359:8)
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
    at Object.errorHandler (/Users/markus/Projects/interaction/node_modules/amqp10/lib/connection.js:290:43)
    at Object.event (/Users/markus/Projects/interaction/node_modules/amqp10/node_modules/stately.js/Stately.js:206:67)
    at Object.event (/Users/markus/Projects/interaction/node_modules/amqp10/node_modules/stately.js/Stately.js:193:52)
```

Haven't still grasped exactly how the connections, sessions and links relate to each other but judging from the log just a few seconds earlier it seems to be transitioning the state on a lot of connections rather than one which seems to be the case for a newly started service. Could it be that it's reusing the session but still ads a connection each time it tries to reconnect?

```
Thu, 13 Aug 2015 15:13:47 GMT amqp10:client connected
Thu, 13 Aug 2015 15:13:47 GMT amqp10:client session already exists, re-using
Thu, 13 Aug 2015 15:13:47 GMT amqp10:framing:amqp Encoding performative: {"descriptor":{"buffer":{"type":"Buffer","data":[0,0,0,0,0,0,0,17]},"offset":0},"value":{"remoteChannel":null,"nextOutgoingId":{"typeName":"uint","value":1},"incomingWindow":{"typeName":"uint","value":100},"outgoingWindow":{"typeName":"uint","value":100},"handleMax":{"typeName":"uint","value":4294967295},"offeredCapabilities":null,"desiredCapabilities":null,"properties":{},"encodeOrdering":["remoteChannel","nextOutgoingId","incomingWindow","outgoingWindow","handleMax","offeredCapabilities","desiredCapabilities","properties"]}}
Thu, 13 Aug 2015 15:13:47 GMT amqp10:framing Sending frame: BeginFrame: {"type":"Buffer","data":[0,0,0,31,2,0,0,23,0,83,17,192,18,8,64,82,1,82,100,82,100,112,255,255,255,255,64,64,193,1,0]}: 0000001f02000017005311c012084052015264526470ffffffff4040c10100
Thu, 13 Aug 2015 15:13:47 GMT amqp10:connection Sending Header 414d515003010000
Thu, 13 Aug 2015 15:13:47 GMT amqp10:connection Transitioning from START to IN_SASL due to connected
Thu, 13 Aug 2015 15:13:47 GMT amqp10:connection Sending Header 414d515003010000
Thu, 13 Aug 2015 15:13:47 GMT amqp10:connection Transitioning from START to IN_SASL due to connected
Thu, 13 Aug 2015 15:13:47 GMT amqp10:connection Sending Header 414d515003010000
Thu, 13 Aug 2015 15:13:47 GMT amqp10:connection Transitioning from START to IN_SASL due to connected
Thu, 13 Aug 2015 15:13:47 GMT amqp10:connection Sending Header 414d515003010000
Thu, 13 Aug 2015 15:13:47 GMT amqp10:connection Transitioning from START to IN_SASL due to connected
Thu, 13 Aug 2015 15:13:47 GMT amqp10:connection Sending Header 414d515003010000
Thu, 13 Aug 2015 15:13:47 GMT amqp10:connection Transitioning from START to IN_SASL due to connected
Thu, 13 Aug 2015 15:13:47 GMT amqp10:connection Sending Header 414d515003010000
Thu, 13 Aug 2015 15:13:47 GMT amqp10:connection Transitioning from START to IN_SASL due to connected
Thu, 13 Aug 2015 15:13:47 GMT amqp10:connection Sending Header 414d515003010000
Thu, 13 Aug 2015 15:13:47 GMT amqp10:connection Transitioning from START to IN_SASL due to connected
Thu, 13 Aug 2015 15:13:47 GMT amqp10:connection Sending Header 414d515003010000
Thu, 13 Aug 2015 15:13:47 GMT amqp10:connection Transitioning from START to IN_SASL due to connected
Thu, 13 Aug 2015 15:13:47 GMT amqp10:connection Sending Header 414d515003010000
Thu, 13 Aug 2015 15:13:47 GMT amqp10:connection Transitioning from START to IN_SASL due to connected
```

**Comment by noodlefrenzy** [comment] 2015-08-14 00:01
This is great feedback, thank you! I'll look into both of these - my guess is I'm failing to detach an event handler from the dead connection when I fire up a new one, _and_ I'm failing to re-use existing handle numbers for dead links (which is only an issue because ServiceBus is bizarrely limited - 1000 vs. the default max_uint).

**Comment by noodlefrenzy** [comment] 2015-08-22 15:26
@markusahlstrand - I just checked in some changes that I _hope_ will fix your issue. I was never able to reproduce it on my end, but I found a few areas in my code where I wasn't cleaning things up as well as I should (connections keeping their event handlers even after being discarded, sessions failing to reset their handles when reconnected).

If you have the time, can you please see if this fixes your problem? In the meantime I'll keep trying to reproduce it on my end.

Thanks for your patience!

**Comment by markusahlstrand** [comment] 2015-08-24 14:45
Hi @noodlefrenzy ,

Tried it for a few hours and it seems stable. Started using it on one of our services and so far it seems fine. I'll send an update after running it for a few days.

Thanks for your work on the stability issues!

**Comment by noodlefrenzy** [comment] 2015-08-24 14:48
Fantastic! Definitely let me know if you see it crop up again or see any other issues. I'll keep this issue open until I hear back from you.

**Comment by mbroadst** [comment] 2015-09-21 12:34
@markusahlstrand any news on this one?

**Comment by markusahlstrand** [comment] 2015-09-21 15:10
We've been running this in production for a service with fairly high throughput for a couple of weeks now and I haven't seen anything in the logs or monitoring, so.. looks great! Any plans on publishing 2.0 on npm?

**Comment by mbroadst** [comment] 2015-09-21 15:16
@markusahlstrand fantastic news! yes @noodlefrenzy and I have had a preliminary discussion about a 2.0 release, I think I'll make a push this week or next.

**Closed by mbroadst** 2015-09-21 15:16 UTC
