### ISSUE TITLE
Client.disconnect leaves link re-attach timeouts running

### ISSUE THREAD

**Issue by noodlefrenzy** [noodlefrenzy/node-amqp10#221] opened 2016-03-02 00:07 UTC
If links set re-attach policies, client disconnect fails to clear those timeouts, leading to cases where the links attempt re-attach on a dead connection/session and causing:

https://github.com/Azure/azure-iot-sdks/issues/320

**Comment by mbroadst** [comment] 2016-03-02 13:02
isn't this a duplicate of #212 ?

**Comment by mbroadst** [comment] 2016-03-02 20:42
@noodlefrenzy I'm not sure that this is happening exactly. If I run the following test:
```
  it('should clear link reattach attempts on client disconnection', function(done) {
    var sender, receiver;
    return test.client.connect(config.address)
      .then(function() {
        return Promise.all([
          test.client.createSender(config.defaultLink),
          test.client.createReceiver(config.defaultLink)
        ]);
      })
      .spread(function(_sender, _receiver) {
        sender = _sender;
        receiver = _receiver;
        return test.client.disconnect();
      })
      .then(function() {
        setTimeout(done, 50000);
      });
  });
```

I don't see any attempts to reattach the links.

What I DO see is an error about attempting to call `_reconnect` in this test:
```
  it('puts the lotion on', function(done) {
    return test.client.connect('amqp://bazoongas')
      .then(function() { return test.client.disconnect(); })
      .then(function() { setTimeout(done, 50000); });
  });
```

with a resulting output of:
```
mbroadst@retinoid:node-amqp10 (master=)$ DEBUG=amqp* SERVER=192.168.1.9 ./node_modules/.bin/mocha test/integration/qpid/client.test.js -t 10000 -g 'lotion'


  QPID
    Client
  amqp10:client connecting to: amqp://bazoongas +0ms
  amqp10:transport:net Connecting to bazoongas:5672 via straight-up sockets +7ms
  amqp10:connection Transitioning from DISCONNECTED to START due to connect +4ms
  amqp10:connection Error from socket: Error: getaddrinfo ENOTFOUND bazoongas bazoongas:5672 +36ms
  amqp10:client connection error:  +1ms { [Error: getaddrinfo ENOTFOUND bazoongas bazoongas:5672]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'bazoongas',
  host: 'bazoongas',
  port: 5672 }
  amqp10:client disconnected +18ms
  amqp10:connection Transitioning from START to DISCONNECTED due to error +1ms
  amqp10:client connecting to: amqp://bazoongas +1ms
  amqp10:transport:net Connecting to bazoongas:5672 via straight-up sockets +1ms
  amqp10:connection Transitioning from DISCONNECTED to START due to connect +0ms
  amqp10:connection Error from socket: Error: getaddrinfo ENOTFOUND bazoongas bazoongas:5672 +1ms
  amqp10:client connection error:  +0ms { [Error: getaddrinfo ENOTFOUND bazoongas bazoongas:5672]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'bazoongas',
  host: 'bazoongas',
  port: 5672 }
  amqp10:client disconnected +1ms
  amqp10:connection Transitioning from START to DISCONNECTED due to error +0ms
  amqp10:client connecting to: amqp://bazoongas +1s
  amqp10:transport:net Connecting to bazoongas:5672 via straight-up sockets +1ms
  amqp10:connection Transitioning from DISCONNECTED to START due to connect +1ms
  amqp10:connection Error from socket: Error: getaddrinfo ENOTFOUND bazoongas bazoongas:5672 +1ms
  amqp10:client connection error:  +0ms { [Error: getaddrinfo ENOTFOUND bazoongas bazoongas:5672]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'bazoongas',
  host: 'bazoongas',
  port: 5672 }
  amqp10:client disconnected +0ms
  amqp10:connection Transitioning from START to DISCONNECTED due to error +0ms
  amqp10:client connecting to: amqp://bazoongas +1s
  amqp10:transport:net Connecting to bazoongas:5672 via straight-up sockets +1ms
  amqp10:connection Transitioning from DISCONNECTED to START due to connect +0ms
  amqp10:connection Error from socket: Error: getaddrinfo ENOTFOUND bazoongas bazoongas:5672 +1ms
  amqp10:client connection error:  +0ms { [Error: getaddrinfo ENOTFOUND bazoongas bazoongas:5672]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'bazoongas',
  host: 'bazoongas',
  port: 5672 }
  amqp10:client disconnected +0ms
  amqp10:connection Transitioning from START to DISCONNECTED due to error +0ms
  amqp10:client connecting to: amqp://bazoongas +2s
  amqp10:transport:net Connecting to bazoongas:5672 via straight-up sockets +1ms
  amqp10:connection Transitioning from DISCONNECTED to START due to connect +0ms
  amqp10:connection Error from socket: Error: getaddrinfo ENOTFOUND bazoongas bazoongas:5672 +1ms
  amqp10:client connection error:  +0ms { [Error: getaddrinfo ENOTFOUND bazoongas bazoongas:5672]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'bazoongas',
  host: 'bazoongas',
  port: 5672 }
  amqp10:client disconnected +0ms
  amqp10:connection Transitioning from START to DISCONNECTED due to error +1ms
  amqp10:client connecting to: amqp://bazoongas +3s
  amqp10:transport:net Connecting to bazoongas:5672 via straight-up sockets +0ms
  amqp10:connection Transitioning from DISCONNECTED to START due to connect +0ms
  amqp10:connection Error from socket: Error: getaddrinfo ENOTFOUND bazoongas bazoongas:5672 +1ms
  amqp10:client connection error:  +0ms { [Error: getaddrinfo ENOTFOUND bazoongas bazoongas:5672]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'bazoongas',
  host: 'bazoongas',
  port: 5672 }
  amqp10:client disconnected +0ms
  amqp10:connection Transitioning from START to DISCONNECTED due to error +0ms
      1) puts the lotion on
  amqp10:client disconnecting +3s
      2) "after each" hook


  0 passing (12s)
  2 failing

  1) QPID Client puts the lotion on:
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.


  2) QPID Client "after each" hook:
     Uncaught TypeError: self._reconnect is not a function
      at AMQPClient._attemptReconnection (lib/amqp_client.js:366:15)
      at null._onTimeout (lib/amqp_client.js:138:21)

```

**Comment by mbroadst** [comment] 2016-03-02 20:42
additionally, we have an error in our address parsing. When I tried just `client.connect('bazoongas')` I get:

```
  amqp10:client connecting to: bazoongas +0ms
Unhandled rejection TypeError: Cannot read property 'slice' of null
    at Object.module.exports.parseAddress (/Users/mbroadst/Development/node/node-amqp10/lib/policies/default_policy.js:112:39)
    at /Users/mbroadst/Development/node/node-amqp10/lib/amqp_client.js:98:31
    at Promise._execute (/Users/mbroadst/Development/node/node-amqp10/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/Users/mbroadst/Development/node/node-amqp10/node_modules/bluebird/js/release/promise.js:474:18)
    at new Promise (/Users/mbroadst/Development/node/node-amqp10/node_modules/bluebird/js/release/promise.js:77:14)
    at AMQPClient.connect (/Users/mbroadst/Development/node/node-amqp10/lib/amqp_client.js:90:10)
    at Context.<anonymous> (/Users/mbroadst/Development/node/node-amqp10/test/integration/qpid/client.test.js:93:24)
    at callFnAsync (/Users/mbroadst/Development/node/node-amqp10/node_modules/mocha/lib/runnable.js:338:8)
    at Test.Runnable.run (/Users/mbroadst/Development/node/node-amqp10/node_modules/mocha/lib/runnable.js:290:7)
    at Runner.runTest (/Users/mbroadst/Development/node/node-amqp10/node_modules/mocha/lib/runner.js:422:10)
    at /Users/mbroadst/Development/node/node-amqp10/node_modules/mocha/lib/runner.js:533:12
    at next (/Users/mbroadst/Development/node/node-amqp10/node_modules/mocha/lib/runner.js:342:14)
    at /Users/mbroadst/Development/node/node-amqp10/node_modules/mocha/lib/runner.js:352:7
    at next (/Users/mbroadst/Development/node/node-amqp10/node_modules/mocha/lib/runner.js:284:14)
    at /Users/mbroadst/Development/node/node-amqp10/node_modules/mocha/lib/runner.js:315:7
    at done (/Users/mbroadst/Development/node/node-amqp10/node_modules/mocha/lib/runnable.js:276:5)
    at callFn (/Users/mbroadst/Development/node/node-amqp10/node_modules/mocha/lib/runnable.js:333:7)
    at Hook.Runnable.run (/Users/mbroadst/Development/node/node-amqp10/node_modules/mocha/lib/runnable.js:308:7)
    at next (/Users/mbroadst/Development/node/node-amqp10/node_modules/mocha/lib/runner.js:298:10)
    at Immediate._onImmediate (/Users/mbroadst/Development/node/node-amqp10/node_modules/mocha/lib/runner.js:320:5)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by noodlefrenzy** [comment] 2016-03-02 23:39
Yes, this is a dupe. Sorry I missed the original. Love `bazoongas` as an address.

What I was seeing was a `setTimeout` call being in-flight as the connection/session gets torn down, then triggering. Seems like we should ensure that `forceDetach` removes any pending timeouts.

**Comment by mbroadst** [comment] 2016-03-03 14:20
@noodlefrenzy yeah, so I immediately pegged that as the location for the fix but I've as of yet been unable to reproduce. Perhaps a unit test would be better for this, I'll give it a shot after lunch

**Closed** 2016-03-05 21:47 UTC
Labels: in progress
