### ISSUE TITLE
Cannot connect to Azure Service Bus

### ISSUE THREAD

**Issue by ragnarol** [noodlefrenzy/node-amqp10#243] opened 2016-06-29 18:22 UTC
Since 27th of June I have started to get an error when I try to create a receiver to one Azure Servicebus subscription.

This has been working flawlessly till now so not sure if the problem is on Azure or the library side.

The error I get is:

> Unable to decode value of 71 from buffer 4210710000000f0000001f0000002f0000003f0000004f0000005f0000006f0000007f0000008f0000009f000000af000000bf000000cf000000df000000ef000000ff at index 12 of array

The code I use to create the receiver is like the following (typescript)

```
    this.connection = this.queueService.instance.connect(this.queueService.uri);

    receive(callback: IQueueHandlerCallback): void {
        this.connection
            .then(() => {
                this.queueService.instance.createReceiver(this.topicName + '/Subscriptions/' + this.subscriptionName).then(receiver => {

                    receiver.on('errorReceived', error => {
                        this.logger.warn('Amqp ===> RX ERROR: ', error);
                        callback(error, null);
                    });

                    // message event handler
                    receiver.on('message', message => {
                        callback(null, message.body.DataString);
                    });
                });
            });
    }
```

Any ideas what that 71 on the payload could be? The subscription is empty so it must be something during negotiation.

Connection is stablished ok, the error comes when creating the receiver

**Comment by mbroadst** [comment] 2016-06-29 18:29
this is a duplicate of https://github.com/noodlefrenzy/node-amqp10/issues/242

It's a problem that the Azure team is working on, please keep discussion limited to that issue thanks!

**Closed by mbroadst** 2016-06-29 18:29 UTC
