### ISSUE TITLE
ServiceBusPolicy should pass through Buffers without JSONifying.

### ISSUE THREAD

**Issue by noodlefrenzy** [noodlefrenzy/node-amqp10#234] opened 2016-04-28 17:38 UTC
Right now they get JSON.stringify'd, which seems wrong and is causing https://github.com/Azure/azure-event-hubs/issues/118

**Comment by geoffreysamper** [comment] 2017-01-07 12:07
Can i send a pull request for this issue?

**Comment by mbroadst** [comment] 2017-01-07 15:49
@geoffreysamper absolutely. We already have this PR #235, but it was unclear whether it resolved the issue brought up here. Would you be willing to verify the fix?

**Comment by geoffreysamper** [comment] 2017-01-07 15:50
Yes i can do it on monday

Op 7 jan. 2017 16:49 schreef "Matt Broadstone" <notifications@github.com>:

**Comment by geoffreysamper** [comment] 2017-01-08 13:44
Hi @mbroadst ,

I tested the PR and for me it works. The problem is not really eventhub but is wat is reading the eventhub. For example we can set the input format of Stream analytics to Avro so what eventhub deliversmust must be avro and not something else. So my suggestion should be if the the body is a buffer then don't jsonify it. 

Is this acceptable for your or do you expect more info or tests?

**Comment by mbroadst** [comment] 2017-01-08 14:08
@geoffreysamper totally fine by me

**Comment by mbroadst** [comment] 2017-01-08 14:10
fixed in 0814658

**Closed by mbroadst** 2017-01-08 14:10 UTC
Labels: bug
